chore(deps): upgrade templ

diff --git a/server/Makefile b/server/Makefile
--- a/server/Makefile
+++ b/server/Makefile
@@ -22,8 +22,13 @@ build-cdn: init
 	go build -ldflags="-w -s" -o ${CDN_BINARY_NAME} ./cmd/cdn/main.go
 
 init:
-	go mod tidy && \
-	go install github.com/a-h/templ/cmd/templ@v0.3.857
+	templ version > /dev/null
+	@if [ $$? != 0 ]; then \
+		echo "templ was not found, installing it..."; \
+		go install github.com/a-h/templ/cmd/templ@v0.3.906; \
+	fi
+
+	go mod tidy
 
 migrate: build-migrator
 	./${MIGRATOR_BINARY_NAME}
diff --git a/web/Makefile b/web/Makefile
--- a/web/Makefile
+++ b/web/Makefile
@@ -11,7 +11,12 @@ generate: tailwindcss-build
 	go generate
 
 init: htmx-init tailwindcss-init
-	go install github.com/a-h/templ/cmd/templ@v0.3.857 && \
+	templ version > /dev/null
+	@if [ $$? != 0 ]; then \
+		echo "templ was not found, installing it..."; \
+		go install github.com/a-h/templ/cmd/templ@v0.3.906; \
+	fi
+
 	go mod tidy && \
 	go generate
 
